### ISSUE TITLE
Bug: 1.5.0 breaks the display of Favicons in Source Mode.

### ISSUE THREAD

**Issue by chrisgrieser** [joethei/obsidian-link-favicon#11]
I noticed that the favicons do not appear in Source Mode anymore. I tested several previous releases and could narrow it down to the 1.5.0 release. In 1.4.4, the favicons still appear.

**Comment by joethei** [comment]
Do you have source mode set as the default editing mode?

**Comment by joethei** [comment]
The main cause of this seems to be that the cm6 extension I am using is only registered when live preview is enabled.
I added this to get some mobile compatibility back (#7).

So if source mode is the default editing mode the extension will not be registered.

I am using the method described in the hub to detect that: 
<https://publish.obsidian.md/hub/04+-+Guides%2C+Workflows%2C+%26+Courses/Guides/How+to+update+your+plugins+and+CSS+for+live+preview#Detect+if+Live+Preview+is+supported>
The heading the seems to be not completely correct, 
since it only return 'true' if live preview the default, not if the new editor is used.
Going to open a PR to the hub with some clarifications.

**Comment by chrisgrieser** [comment]
> Do you have source mode set as the default editing mode?

Yes

**Comment by joethei** [comment]
I improved the detection of the used editor, this is now fixed.

**Comment by chrisgrieser** [comment]
thanks! ☺️
