### ISSUE TITLE
FR: invert favicon color depending on background

### ISSUE THREAD

**Issue by chrisgrieser** [joethei/obsidian-link-favicon#5]
I noticed that with some favicons, you can get unlucky and get a white favicon on a white note background, which is hard to read Example:
<img width="305" alt="Screenshot 2022-01-02 16 09 31" src="https://user-images.githubusercontent.com/73286100/147880108-7925eb30-1e34-4c42-8464-784300e446a1.png">

While I can apply a color-inverting filter for individual sites via CSS, I am wondering whether it might be possible for the plugin solve this? For example by detecting theme background color & applying a color inversion filter when the favicon is of a similar color?

**Comment by joethei** [comment]
I tried implementing this a few weeks back, but always ran into some problems.
With the announcement off v0.13.25 this seems to be way easier now.

**Comment by joethei** [comment]
I was correct, this is now working with 1.6.0 and obsidian v0.13.25.
If you want to tweak it, all images generated by the plugin have a bunch of data attributes and I could add more if required.

I would not recommend just using an inversion, 
especially not with the basic `is-dark`/`is-light` attributes.
Otherwise some interesting results will occur.
![](https://i.joethei.space/8vYMZrvV40.png)

**Comment by chrisgrieser** [comment]
I'll look into it with the next public release. Thanks! (I simply do not have the time to participate in the bug hunting of insider releases :( )

**Comment by NomarCub** [comment]
For anyone interested I found this CSS to be decent at inverting (and rotating the hue to preserve the original color scheme).

```css
filter: invert(1) hue-rotate(180deg);
```

**Comment by joethei** [comment]
That is the css I have used, just the other way around 👀

**Comment by joethei** [comment]
Just did a test and to confirm, the version included in the plugin looks the same.
